# Generated by Django 5.0.6 on 2024-06-03 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_home', '0002_alter_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
