# Generated by Django 5.0.6 on 2024-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_home', '0003_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
