# Generated by Django 5.0 on 2024-06-06 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_home', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
