# Generated by Django 5.0 on 2024-06-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_home', '0008_alter_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
